# Generated by Django 4.1 on 2022-08-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('uuid', models.UUIDField(default=todo_list.models._new_uuid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'default_related_name': 'lists',
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('uuid', models.UUIDField(default=todo_list.models._new_uuid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.todolist')),
            ],
            options={
                'ordering': ['created'],
                'default_related_name': 'items',
                'unique_together': {('list', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=todo_list.models._new_uuid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.todoitem')),
            ],
            options={
                'ordering': ['-created'],
                'default_related_name': 'comments',
            },
        ),
    ]
